export type Category =
  | 'alkali'
  | 'alkaline'
  | 'transition'
  | 'post-transition'
  | 'metalloid'
  | 'nonmetal'
  | 'halogen'
  | 'noble'
  | 'lanthanide'
  | 'actinide'
  | 'unknown';

export interface Element {
  number: number;
  symbol: string;
  name: string;
  mass: string;
  category: Category;
  col: number;
  row: number;
  // Abondance dans la croûte terrestre, en % massique (chaîne prête à afficher).
  abundance?: string;
  // Molécules courantes contenant l'élément.
  molecules?: string[];
  // Principales applications humaines.
  applications?: string;
}

export const ELEMENTS: Element[] = [
  { number: 1, symbol: 'H', name: 'Hydrogène', mass: '1.008', category: 'nonmetal', col: 1, row: 1 },
  { number: 2, symbol: 'He', name: 'Hélium', mass: '4.003', category: 'noble', col: 18, row: 1 },
  { number: 3, symbol: 'Li', name: 'Lithium', mass: '6.94', category: 'alkali', col: 1, row: 2 },
  { number: 4, symbol: 'Be', name: 'Béryllium', mass: '9.012', category: 'alkaline', col: 2, row: 2 },
  { number: 5, symbol: 'B', name: 'Bore', mass: '10.81', category: 'metalloid', col: 13, row: 2 },
  { number: 6, symbol: 'C', name: 'Carbone', mass: '12.011', category: 'nonmetal', col: 14, row: 2 },
  { number: 7, symbol: 'N', name: 'Azote', mass: '14.007', category: 'nonmetal', col: 15, row: 2 },
  { number: 8, symbol: 'O', name: 'Oxygène', mass: '15.999', category: 'nonmetal', col: 16, row: 2 },
  { number: 9, symbol: 'F', name: 'Fluor', mass: '18.998', category: 'halogen', col: 17, row: 2 },
  { number: 10, symbol: 'Ne', name: 'Néon', mass: '20.180', category: 'noble', col: 18, row: 2 },
  { number: 11, symbol: 'Na', name: 'Sodium', mass: '22.990', category: 'alkali', col: 1, row: 3 },
  { number: 12, symbol: 'Mg', name: 'Magnésium', mass: '24.305', category: 'alkaline', col: 2, row: 3 },
  { number: 13, symbol: 'Al', name: 'Aluminium', mass: '26.982', category: 'post-transition', col: 13, row: 3 },
  { number: 14, symbol: 'Si', name: 'Silicium', mass: '28.085', category: 'metalloid', col: 14, row: 3 },
  { number: 15, symbol: 'P', name: 'Phosphore', mass: '30.974', category: 'nonmetal', col: 15, row: 3 },
  { number: 16, symbol: 'S', name: 'Soufre', mass: '32.06', category: 'nonmetal', col: 16, row: 3 },
  { number: 17, symbol: 'Cl', name: 'Chlore', mass: '35.45', category: 'halogen', col: 17, row: 3 },
  { number: 18, symbol: 'Ar', name: 'Argon', mass: '39.948', category: 'noble', col: 18, row: 3 },
  { number: 19, symbol: 'K', name: 'Potassium', mass: '39.098', category: 'alkali', col: 1, row: 4 },
  { number: 20, symbol: 'Ca', name: 'Calcium', mass: '40.078', category: 'alkaline', col: 2, row: 4 },
  { number: 21, symbol: 'Sc', name: 'Scandium', mass: '44.956', category: 'transition', col: 3, row: 4 },
  { number: 22, symbol: 'Ti', name: 'Titane', mass: '47.867', category: 'transition', col: 4, row: 4 },
  { number: 23, symbol: 'V', name: 'Vanadium', mass: '50.942', category: 'transition', col: 5, row: 4 },
  { number: 24, symbol: 'Cr', name: 'Chrome', mass: '51.996', category: 'transition', col: 6, row: 4 },
  { number: 25, symbol: 'Mn', name: 'Manganèse', mass: '54.938', category: 'transition', col: 7, row: 4 },
  { number: 26, symbol: 'Fe', name: 'Fer', mass: '55.845', category: 'transition', col: 8, row: 4 },
  { number: 27, symbol: 'Co', name: 'Cobalt', mass: '58.933', category: 'transition', col: 9, row: 4 },
  { number: 28, symbol: 'Ni', name: 'Nickel', mass: '58.693', category: 'transition', col: 10, row: 4 },
  { number: 29, symbol: 'Cu', name: 'Cuivre', mass: '63.546', category: 'transition', col: 11, row: 4 },
  { number: 30, symbol: 'Zn', name: 'Zinc', mass: '65.38', category: 'transition', col: 12, row: 4 },
  { number: 31, symbol: 'Ga', name: 'Gallium', mass: '69.723', category: 'post-transition', col: 13, row: 4 },
  { number: 32, symbol: 'Ge', name: 'Germanium', mass: '72.630', category: 'metalloid', col: 14, row: 4 },
  { number: 33, symbol: 'As', name: 'Arsenic', mass: '74.922', category: 'metalloid', col: 15, row: 4 },
  { number: 34, symbol: 'Se', name: 'Sélénium', mass: '78.971', category: 'nonmetal', col: 16, row: 4 },
  { number: 35, symbol: 'Br', name: 'Brome', mass: '79.904', category: 'halogen', col: 17, row: 4 },
  { number: 36, symbol: 'Kr', name: 'Krypton', mass: '83.798', category: 'noble', col: 18, row: 4 },
  { number: 37, symbol: 'Rb', name: 'Rubidium', mass: '85.468', category: 'alkali', col: 1, row: 5 },
  { number: 38, symbol: 'Sr', name: 'Strontium', mass: '87.62', category: 'alkaline', col: 2, row: 5 },
  { number: 39, symbol: 'Y', name: 'Yttrium', mass: '88.906', category: 'transition', col: 3, row: 5 },
  { number: 40, symbol: 'Zr', name: 'Zirconium', mass: '91.224', category: 'transition', col: 4, row: 5 },
  { number: 41, symbol: 'Nb', name: 'Niobium', mass: '92.906', category: 'transition', col: 5, row: 5 },
  { number: 42, symbol: 'Mo', name: 'Molybdène', mass: '95.95', category: 'transition', col: 6, row: 5 },
  { number: 43, symbol: 'Tc', name: 'Technétium', mass: '98', category: 'transition', col: 7, row: 5 },
  { number: 44, symbol: 'Ru', name: 'Ruthénium', mass: '101.07', category: 'transition', col: 8, row: 5 },
  { number: 45, symbol: 'Rh', name: 'Rhodium', mass: '102.91', category: 'transition', col: 9, row: 5 },
  { number: 46, symbol: 'Pd', name: 'Palladium', mass: '106.42', category: 'transition', col: 10, row: 5 },
  { number: 47, symbol: 'Ag', name: 'Argent', mass: '107.87', category: 'transition', col: 11, row: 5 },
  { number: 48, symbol: 'Cd', name: 'Cadmium', mass: '112.41', category: 'transition', col: 12, row: 5 },
  { number: 49, symbol: 'In', name: 'Indium', mass: '114.82', category: 'post-transition', col: 13, row: 5 },
  { number: 50, symbol: 'Sn', name: 'Étain', mass: '118.71', category: 'post-transition', col: 14, row: 5 },
  { number: 51, symbol: 'Sb', name: 'Antimoine', mass: '121.76', category: 'metalloid', col: 15, row: 5 },
  { number: 52, symbol: 'Te', name: 'Tellure', mass: '127.60', category: 'metalloid', col: 16, row: 5 },
  { number: 53, symbol: 'I', name: 'Iode', mass: '126.90', category: 'halogen', col: 17, row: 5 },
  { number: 54, symbol: 'Xe', name: 'Xénon', mass: '131.29', category: 'noble', col: 18, row: 5 },
  { number: 55, symbol: 'Cs', name: 'Césium', mass: '132.91', category: 'alkali', col: 1, row: 6 },
  { number: 56, symbol: 'Ba', name: 'Baryum', mass: '137.33', category: 'alkaline', col: 2, row: 6 },
  { number: 57, symbol: 'La', name: 'Lanthane', mass: '138.91', category: 'lanthanide', col: 3, row: 6 },
  { number: 72, symbol: 'Hf', name: 'Hafnium', mass: '178.49', category: 'transition', col: 4, row: 6 },
  { number: 73, symbol: 'Ta', name: 'Tantale', mass: '180.95', category: 'transition', col: 5, row: 6 },
  { number: 74, symbol: 'W', name: 'Tungstène', mass: '183.84', category: 'transition', col: 6, row: 6 },
  { number: 75, symbol: 'Re', name: 'Rhénium', mass: '186.21', category: 'transition', col: 7, row: 6 },
  { number: 76, symbol: 'Os', name: 'Osmium', mass: '190.23', category: 'transition', col: 8, row: 6 },
  { number: 77, symbol: 'Ir', name: 'Iridium', mass: '192.22', category: 'transition', col: 9, row: 6 },
  { number: 78, symbol: 'Pt', name: 'Platine', mass: '195.08', category: 'transition', col: 10, row: 6 },
  { number: 79, symbol: 'Au', name: 'Or', mass: '196.97', category: 'transition', col: 11, row: 6 },
  { number: 80, symbol: 'Hg', name: 'Mercure', mass: '200.59', category: 'transition', col: 12, row: 6 },
  { number: 81, symbol: 'Tl', name: 'Thallium', mass: '204.38', category: 'post-transition', col: 13, row: 6 },
  { number: 82, symbol: 'Pb', name: 'Plomb', mass: '207.2', category: 'post-transition', col: 14, row: 6 },
  { number: 83, symbol: 'Bi', name: 'Bismuth', mass: '208.98', category: 'post-transition', col: 15, row: 6 },
  { number: 84, symbol: 'Po', name: 'Polonium', mass: '209', category: 'post-transition', col: 16, row: 6 },
  { number: 85, symbol: 'At', name: 'Astate', mass: '210', category: 'halogen', col: 17, row: 6 },
  { number: 86, symbol: 'Rn', name: 'Radon', mass: '222', category: 'noble', col: 18, row: 6 },
  { number: 87, symbol: 'Fr', name: 'Francium', mass: '223', category: 'alkali', col: 1, row: 7 },
  { number: 88, symbol: 'Ra', name: 'Radium', mass: '226', category: 'alkaline', col: 2, row: 7 },
  { number: 89, symbol: 'Ac', name: 'Actinium', mass: '227', category: 'actinide', col: 3, row: 7 },
  { number: 104, symbol: 'Rf', name: 'Rutherfordium', mass: '267', category: 'transition', col: 4, row: 7 },
  { number: 105, symbol: 'Db', name: 'Dubnium', mass: '268', category: 'transition', col: 5, row: 7 },
  { number: 106, symbol: 'Sg', name: 'Seaborgium', mass: '269', category: 'transition', col: 6, row: 7 },
  { number: 107, symbol: 'Bh', name: 'Bohrium', mass: '270', category: 'transition', col: 7, row: 7 },
  { number: 108, symbol: 'Hs', name: 'Hassium', mass: '269', category: 'transition', col: 8, row: 7 },
  { number: 109, symbol: 'Mt', name: 'Meitnerium', mass: '278', category: 'unknown', col: 9, row: 7 },
  { number: 110, symbol: 'Ds', name: 'Darmstadtium', mass: '281', category: 'unknown', col: 10, row: 7 },
  { number: 111, symbol: 'Rg', name: 'Roentgenium', mass: '282', category: 'unknown', col: 11, row: 7 },
  { number: 112, symbol: 'Cn', name: 'Copernicium', mass: '285', category: 'transition', col: 12, row: 7 },
  { number: 113, symbol: 'Nh', name: 'Nihonium', mass: '286', category: 'unknown', col: 13, row: 7 },
  { number: 114, symbol: 'Fl', name: 'Flérovium', mass: '289', category: 'unknown', col: 14, row: 7 },
  { number: 115, symbol: 'Mc', name: 'Moscovium', mass: '290', category: 'unknown', col: 15, row: 7 },
  { number: 116, symbol: 'Lv', name: 'Livermorium', mass: '293', category: 'unknown', col: 16, row: 7 },
  { number: 117, symbol: 'Ts', name: 'Tennesse', mass: '294', category: 'unknown', col: 17, row: 7 },
  { number: 118, symbol: 'Og', name: 'Oganesson', mass: '294', category: 'unknown', col: 18, row: 7 },
  // Lanthanides (rangée détachée)
  { number: 58, symbol: 'Ce', name: 'Cérium', mass: '140.12', category: 'lanthanide', col: 4, row: 9 },
  { number: 59, symbol: 'Pr', name: 'Praséodyme', mass: '140.91', category: 'lanthanide', col: 5, row: 9 },
  { number: 60, symbol: 'Nd', name: 'Néodyme', mass: '144.24', category: 'lanthanide', col: 6, row: 9 },
  { number: 61, symbol: 'Pm', name: 'Prométhium', mass: '145', category: 'lanthanide', col: 7, row: 9 },
  { number: 62, symbol: 'Sm', name: 'Samarium', mass: '150.36', category: 'lanthanide', col: 8, row: 9 },
  { number: 63, symbol: 'Eu', name: 'Europium', mass: '151.96', category: 'lanthanide', col: 9, row: 9 },
  { number: 64, symbol: 'Gd', name: 'Gadolinium', mass: '157.25', category: 'lanthanide', col: 10, row: 9 },
  { number: 65, symbol: 'Tb', name: 'Terbium', mass: '158.93', category: 'lanthanide', col: 11, row: 9 },
  { number: 66, symbol: 'Dy', name: 'Dysprosium', mass: '162.50', category: 'lanthanide', col: 12, row: 9 },
  { number: 67, symbol: 'Ho', name: 'Holmium', mass: '164.93', category: 'lanthanide', col: 13, row: 9 },
  { number: 68, symbol: 'Er', name: 'Erbium', mass: '167.26', category: 'lanthanide', col: 14, row: 9 },
  { number: 69, symbol: 'Tm', name: 'Thulium', mass: '168.93', category: 'lanthanide', col: 15, row: 9 },
  { number: 70, symbol: 'Yb', name: 'Ytterbium', mass: '173.05', category: 'lanthanide', col: 16, row: 9 },
  { number: 71, symbol: 'Lu', name: 'Lutécium', mass: '174.97', category: 'lanthanide', col: 17, row: 9 },
  // Actinides (rangée détachée)
  { number: 90, symbol: 'Th', name: 'Thorium', mass: '232.04', category: 'actinide', col: 4, row: 10 },
  { number: 91, symbol: 'Pa', name: 'Protactinium', mass: '231.04', category: 'actinide', col: 5, row: 10 },
  { number: 92, symbol: 'U', name: 'Uranium', mass: '238.03', category: 'actinide', col: 6, row: 10 },
  { number: 93, symbol: 'Np', name: 'Neptunium', mass: '237', category: 'actinide', col: 7, row: 10 },
  { number: 94, symbol: 'Pu', name: 'Plutonium', mass: '244', category: 'actinide', col: 8, row: 10 },
  { number: 95, symbol: 'Am', name: 'Américium', mass: '243', category: 'actinide', col: 9, row: 10 },
  { number: 96, symbol: 'Cm', name: 'Curium', mass: '247', category: 'actinide', col: 10, row: 10 },
  { number: 97, symbol: 'Bk', name: 'Berkélium', mass: '247', category: 'actinide', col: 11, row: 10 },
  { number: 98, symbol: 'Cf', name: 'Californium', mass: '251', category: 'actinide', col: 12, row: 10 },
  { number: 99, symbol: 'Es', name: 'Einsteinium', mass: '252', category: 'actinide', col: 13, row: 10 },
  { number: 100, symbol: 'Fm', name: 'Fermium', mass: '257', category: 'actinide', col: 14, row: 10 },
  { number: 101, symbol: 'Md', name: 'Mendélévium', mass: '258', category: 'actinide', col: 15, row: 10 },
  { number: 102, symbol: 'No', name: 'Nobélium', mass: '259', category: 'actinide', col: 16, row: 10 },
  { number: 103, symbol: 'Lr', name: 'Lawrencium', mass: '266', category: 'actinide', col: 17, row: 10 },
];

export const CATEGORY_LABELS: Record<Category, string> = {
  alkali: 'Métaux alcalins',
  alkaline: 'Métaux alcalino-terreux',
  transition: 'Métaux de transition',
  'post-transition': 'Métaux pauvres',
  metalloid: 'Métalloïdes',
  nonmetal: 'Non-métaux',
  halogen: 'Halogènes',
  noble: 'Gaz nobles',
  lanthanide: 'Lanthanides',
  actinide: 'Actinides',
  unknown: 'Inconnus',
};

// Enrichissement : abondance dans la croûte terrestre (% massique) et molécules courantes.
// Renseigné pour les éléments où la donnée est pertinente ; les autres restent sans valeur.
const ELEMENT_EXTRA: Record<number, { abundance?: string; molecules?: string[] }> = {
  1: { abundance: '0.14 %', molecules: ['H₂', 'H₂O', 'CH₄', 'NH₃'] },
  2: { abundance: '≈ 0 % (traces)', molecules: [] },
  3: { abundance: '0.0017 %', molecules: ['Li₂CO₃', 'LiCl'] },
  4: { abundance: '0.00019 %', molecules: ['BeO'] },
  5: { abundance: '0.001 %', molecules: ['B₂O₃', 'H₃BO₃'] },
  6: { abundance: '0.02 %', molecules: ['CO₂', 'CH₄', 'CaCO₃', 'C₆H₁₂O₆'] },
  7: { abundance: '0.0019 %', molecules: ['N₂', 'NH₃', 'NO₂', 'HNO₃'] },
  8: { abundance: '46.1 %', molecules: ['O₂', 'H₂O', 'CO₂', 'SiO₂'] },
  9: { abundance: '0.0585 %', molecules: ['HF', 'CaF₂'] },
  10: { abundance: '≈ 0 % (traces)', molecules: [] },
  11: { abundance: '2.36 %', molecules: ['NaCl', 'NaOH', 'Na₂CO₃'] },
  12: { abundance: '2.33 %', molecules: ['MgO', 'MgCl₂', 'MgSO₄'] },
  13: { abundance: '8.23 %', molecules: ['Al₂O₃'] },
  14: { abundance: '28.2 %', molecules: ['SiO₂', 'SiC'] },
  15: { abundance: '0.105 %', molecules: ['H₃PO₄', 'P₄', 'Ca₃(PO₄)₂'] },
  16: { abundance: '0.035 %', molecules: ['H₂SO₄', 'SO₂', 'H₂S'] },
  17: { abundance: '0.0145 %', molecules: ['NaCl', 'HCl'] },
  18: { abundance: '≈ 0 % (traces)', molecules: [] },
  19: { abundance: '2.09 %', molecules: ['KCl', 'KOH', 'KNO₃'] },
  20: { abundance: '4.15 %', molecules: ['CaCO₃', 'CaO', 'Ca(OH)₂'] },
  22: { abundance: '0.565 %', molecules: ['TiO₂'] },
  24: { abundance: '0.0102 %', molecules: ['Cr₂O₃'] },
  25: { abundance: '0.095 %', molecules: ['MnO₂'] },
  26: { abundance: '5.63 %', molecules: ['Fe₂O₃', 'Fe₃O₄', 'FeS₂'] },
  27: { abundance: '0.0025 %', molecules: ['CoO'] },
  28: { abundance: '0.0084 %', molecules: ['NiO'] },
  29: { abundance: '0.006 %', molecules: ['CuSO₄', 'Cu₂O'] },
  30: { abundance: '0.007 %', molecules: ['ZnO', 'ZnS'] },
  35: { abundance: '0.00024 %', molecules: ['NaBr', 'HBr'] },
  38: { abundance: '0.037 %', molecules: ['SrCO₃', 'SrSO₄'] },
  47: { abundance: '0.0000075 %', molecules: ['AgNO₃', 'AgCl'] },
  53: { abundance: '0.000045 %', molecules: ['KI', 'HI'] },
  56: { abundance: '0.0425 %', molecules: ['BaSO₄', 'BaCO₃'] },
  79: { abundance: '0.0000004 %', molecules: [] },
  80: { abundance: '0.0000085 %', molecules: ['HgS'] },
  82: { abundance: '0.0014 %', molecules: ['PbO', 'PbS'] },
  92: { abundance: '0.00018 %', molecules: ['UO₂', 'UF₆'] },
};

// Applications humaines, surtout pour les éléments non couverts par ELEMENT_EXTRA.
const ELEMENT_APPLICATIONS: Record<number, string> = {
  21: 'Alliages aluminium-scandium pour l’aéronautique et le sport',
  23: 'Aciers à outils résistants, catalyseurs chimiques',
  31: 'Semi-conducteurs, LED, cellules photovoltaïques',
  32: 'Fibres optiques, optique et détecteurs infrarouges',
  33: 'Semi-conducteurs, anciens pesticides et conservateurs du bois',
  34: 'Électronique, coloration du verre, compléments alimentaires',
  36: 'Éclairage (lampes, flashs photo), lasers',
  37: 'Horloges atomiques, cellules photoélectriques',
  39: 'LED et écrans, supraconducteurs, lasers YAG',
  40: 'Gaines de combustible nucléaire, céramiques techniques',
  41: 'Aciers alliés, aimants supraconducteurs (IRM)',
  42: 'Aciers à haute résistance, catalyseurs',
  43: 'Imagerie médicale (scintigraphie au technétium-99m)',
  44: 'Contacts électriques, catalyseurs, disques durs',
  45: 'Pots catalytiques automobiles, bijouterie',
  46: 'Pots catalytiques, électronique, bijouterie',
  48: 'Batteries Ni-Cd, pigments, revêtements anticorrosion',
  49: 'Écrans tactiles et LCD (oxyde ITO), soudures',
  50: 'Soudure électronique, fer-blanc, alliages (bronze)',
  51: 'Retardateurs de flamme, alliages de plomb',
  52: 'Alliages, panneaux solaires (tellurure de cadmium)',
  54: 'Éclairage, anesthésie, propulsion ionique spatiale',
  55: 'Horloges atomiques, fluides de forage pétrolier',
  57: 'Optique de précision, batteries NiMH, catalyseurs',
  58: 'Catalyseurs (pots d’échappement), polissage du verre',
  59: 'Aimants puissants, coloration des verres',
  60: 'Aimants permanents néodyme très puissants',
  61: 'Piles nucléaires, peintures luminescentes',
  62: 'Aimants haute performance, barres de contrôle nucléaires',
  63: 'Luminophores rouges des écrans, marquage anti-contrefaçon',
  64: 'Agent de contraste en IRM, blindages nucléaires',
  65: 'Luminophores verts, alliages d’aimants',
  66: 'Aimants résistants à la chaleur, disques durs',
  67: 'Aimants, lasers médicaux et dentaires',
  68: 'Amplificateurs de fibres optiques, lasers',
  69: 'Lasers, sources portables de rayons X',
  70: 'Lasers, horloges atomiques, aciers inoxydables',
  71: 'Catalyseurs de raffinage, imagerie médicale TEP',
  72: 'Barres de contrôle nucléaires, semi-conducteurs',
  73: 'Condensateurs électroniques, implants médicaux',
  74: 'Filaments, outils de coupe, blindages (tungstène)',
  75: 'Superalliages de turbines, catalyseurs',
  76: 'Alliages très durs (pointes de stylo, contacts)',
  77: 'Bougies d’allumage, creusets, électrodes',
  78: 'Pots catalytiques, bijouterie, électrodes, chimiothérapie',
  81: 'Détecteurs infrarouges (ancienne mort-aux-rats)',
  83: 'Médicaments gastriques, alliages à bas point de fusion',
  84: 'Sources de chaleur, éliminateurs d’électricité statique',
  85: 'Recherche (radiothérapie ciblée expérimentale)',
  86: 'Radiothérapie historique, traceur en géologie',
  87: 'Recherche scientifique uniquement',
  88: 'Ancienne peinture luminescente, radiothérapie historique',
  89: 'Sources de neutrons, radiothérapie (actinium-225)',
  90: 'Combustible nucléaire potentiel, anciens manchons à gaz',
  91: 'Recherche scientifique uniquement',
  93: 'Détecteurs de neutrons, recherche',
  94: 'Armes et combustible nucléaires, générateurs RTG spatiaux',
  95: 'Détecteurs de fumée domestiques',
  96: 'Générateurs thermoélectriques des sondes spatiales',
  97: 'Recherche scientifique uniquement',
  98: 'Sources de neutrons (démarrage de réacteurs, analyse)',
  99: 'Recherche scientifique uniquement',
  100: 'Recherche scientifique uniquement',
  101: 'Recherche scientifique uniquement',
  102: 'Recherche scientifique uniquement',
  103: 'Recherche scientifique uniquement',
  104: 'Recherche scientifique uniquement',
  105: 'Recherche scientifique uniquement',
  106: 'Recherche scientifique uniquement',
  107: 'Recherche scientifique uniquement',
  108: 'Recherche scientifique uniquement',
  109: 'Recherche scientifique uniquement',
  110: 'Recherche scientifique uniquement',
  111: 'Recherche scientifique uniquement',
  112: 'Recherche scientifique uniquement',
  113: 'Recherche scientifique uniquement',
  114: 'Recherche scientifique uniquement',
  115: 'Recherche scientifique uniquement',
  116: 'Recherche scientifique uniquement',
  117: 'Recherche scientifique uniquement',
  118: 'Recherche scientifique uniquement',
};

// Nom commun français des molécules, pour affichage entre parenthèses.
export const MOLECULE_NAMES: Record<string, string> = {
  'H₂': 'dihydrogène',
  'H₂O': 'eau',
  'CH₄': 'méthane',
  'NH₃': 'ammoniac',
  'Li₂CO₃': 'carbonate de lithium',
  'LiCl': 'chlorure de lithium',
  'BeO': 'oxyde de béryllium',
  'B₂O₃': 'oxyde de bore',
  'H₃BO₃': 'acide borique',
  'CO₂': 'dioxyde de carbone',
  'CaCO₃': 'calcaire',
  'C₆H₁₂O₆': 'glucose',
  'N₂': 'diazote',
  'NO₂': "dioxyde d'azote",
  'HNO₃': 'acide nitrique',
  'O₂': 'dioxygène',
  'SiO₂': 'silice',
  'HF': 'acide fluorhydrique',
  'CaF₂': 'fluorine',
  'NaCl': 'sel de table',
  'NaOH': 'soude',
  'Na₂CO₃': 'carbonate de sodium',
  'MgO': 'magnésie',
  'MgCl₂': 'chlorure de magnésium',
  'MgSO₄': "sel d'Epsom",
  'Al₂O₃': 'alumine',
  'SiC': 'carbure de silicium',
  'H₃PO₄': 'acide phosphorique',
  'P₄': 'phosphore blanc',
  'Ca₃(PO₄)₂': 'phosphate de calcium',
  'H₂SO₄': 'acide sulfurique',
  'SO₂': 'dioxyde de soufre',
  'H₂S': "sulfure d'hydrogène",
  'HCl': 'acide chlorhydrique',
  'KCl': 'chlorure de potassium',
  'KOH': 'potasse',
  'KNO₃': 'salpêtre',
  'CaO': 'chaux vive',
  'Ca(OH)₂': 'chaux éteinte',
  'TiO₂': 'dioxyde de titane',
  'Cr₂O₃': 'oxyde de chrome',
  'MnO₂': 'dioxyde de manganèse',
  'Fe₂O₃': 'hématite',
  'Fe₃O₄': 'magnétite',
  'FeS₂': 'pyrite',
  'CoO': 'oxyde de cobalt',
  'NiO': 'oxyde de nickel',
  'CuSO₄': 'sulfate de cuivre',
  'Cu₂O': 'oxyde de cuivre(I)',
  'ZnO': 'oxyde de zinc',
  'ZnS': 'blende',
  'NaBr': 'bromure de sodium',
  'HBr': 'acide bromhydrique',
  'SrCO₃': 'carbonate de strontium',
  'SrSO₄': 'célestine',
  'AgNO₃': "nitrate d'argent",
  'AgCl': "chlorure d'argent",
  'KI': 'iodure de potassium',
  'HI': 'acide iodhydrique',
  'BaSO₄': 'barytine',
  'BaCO₃': 'carbonate de baryum',
  'HgS': 'cinabre',
  'PbO': 'oxyde de plomb',
  'PbS': 'galène',
  'UO₂': "dioxyde d'uranium",
  'UF₆': "hexafluorure d'uranium",
};

export function getElement(number: number): Element | undefined {
  const base = ELEMENTS.find((el) => el.number === number);
  if (!base) return undefined;
  const applications = ELEMENT_APPLICATIONS[number];
  return { ...base, ...ELEMENT_EXTRA[number], ...(applications ? { applications } : {}) };
}
